name: PrismaCloud
on:
  pull_request:
  push:
    branches:
      - master    
jobs:
  scan:
    runs-on: ubuntu-latest 
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
     
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Prisma Cloud
      id: Prisma_Cloud
      uses: bridgecrewio/checkov-action@master
      env:
        PRISMA_API_URL: https://api3.prismacloud.io
      with:
        api-key: ${{ secrets.BC_API_KEY }}
        directory: terraform/
        #soft_fail: true
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      
      # Results are generated only on a success or failure
      # this is required since GitHub by default won't run the next step
      # when the previous one has failed. Alternatively, enable soft_fail in BC action.
      if: success() || failure()
      with:
        sarif_file: results.sarif
